name: check-new-versions



on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'test'  
      ref:
        description: 'test'  
        default: 'warning'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test dispatch
      env:
        KEY4HEP_COMMENT_BOT_TOKEN: ${{ secrets.KEY4HEP_COMMENT_BOT_TOKEN }}
      run: |
        git fetch origin pull/${{ github.event.inputs.ref }}/head:testbranch${{ github.event.inputs.ref }}
        git checkout testbranch${{ github.event.inputs.ref }}
        echo "Tags: ${{ github.event.inputs.ref }}" 
        echo $GITHUB_HEAD_REF
        echo $GITHUB_EVENT_PATH
        cat README.md
